# Generated by Django 4.0.3 on 2022-04-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=30, verbose_name='Apellido')),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField(verbose_name='Año de nacimiento')),
                ('link', models.CharField(max_length=30, verbose_name='Parentezco')),
            ],
        ),
    ]
